export const interests = [
  "3D Printing",
  "Acrobatics",
  "Acting",
  "Aerobics",
  "Airsoft",
  "Animation",
  "Anime",
  "Antiquing",
  "Aquariums",
  "Archery",
  "Architecture",
  "Arts and Crafts",
  "Astrology",
  "Astronomy",
  "Astrophotography",
  "Backpacking",
  "Badminton",
  "Baking",
  "Ballet",
  "Ballroom Dancing",
  "Barbecuing",
  "Bartending",
  "Baseball",
  "Basketball",
  "Beatboxing",
  "Beekeeping",
  "Beer Brewing",
  "Billiards",
  "Birdwatching",
  "Blogging",
  "BMX",
  "Board Games",
  "Boating",
  "Bodybuilding",
  "Bonsai",
  "Bookbinding",
  "Bowling",
  "Boxing",
  "Bullet Journaling",
  "Calligraphy",
  "Camping",
  "Candle Making",
  "Canoeing",
  "Card Games",
  "Cars",
  "Caving",
  "Ceramics",
  "Cheerleading",
  "Chess",
  "Climbing",
  "Coding",
  "Coffee Roasting",
  "Coin Collecting",
  "Collecting",
  "Comedy",
  "Comics",
  "Cooking",
  "Cosplay",
  "Crafting",
  "Creative Writing",
  "Cricket",
  "Crocheting",
  "Cross-stitch",
  "CrossFit",
  "Cycling",
  "Dancing",
  "Darts",
  "Debating",
  "DIY Projects",
  "DJing",
  "Drawing",
  "Drone Flying",
  "Drumming",
  "Dungeons & Dragons",
  "Electronics",
  "Embroidery",
  "Equestrianism",
  "Esports",
  "Fashion",
  "Fencing",
  "Figure Skating",
  "Filmmaking",
  "Fishing",
  "Fitness",
  "Flower Arranging",
  "Flying",
  "Foraging",
  "Football",
  "Gaming",
  "Gardening",
  "Genealogy",
  "Geocaching",
  "Golf",
  "Graphic Design",
  "Guitar",
  "Gymnastics",
  "Handball",
  "Hiking",
  "History",
  "Hockey",
  "Home Brewing",
  "Horse Riding",
  "Hunting",
  "Ice Hockey",
  "Ice Skating",
  "Interior Design",
  "Jewelry Making",
  "Jogging",
  "Journaling",
  "Judo",
  "Juggling",
  "Karaoke",
  "Karate",
  "Kayaking",
  "Kickboxing",
  "Kitesurfing",
  "Knitting",
  "Lacrosse",
  "Language Learning",
  "Leatherworking",
  "Lego Building",
  "Magic",
  "Makeup",
  "Manga",
  "Martial Arts",
  "Meditation",
  "Metalworking",
  "Mixology",
  "Model Building",
  "Motorcycling",
  "Mountain Biking",
  "Mountaineering",
  "Movies",
  "Museums",
  "Music",
  "Music Production",
  "Nail Art",
  "Netball",
  "Networking",
  "Origami",
  "Painting",
  "Paragliding",
  "Parkour",
  "Performing Arts",
  "Pet Care",
  "Philosophy",
  "Photography",
  "Pilates",
  "Podcasting",
  "Poetry",
  "Poker",
  "Pottery",
  "Programming",
  "Public Speaking",
  "Puzzles",
  "Quilting",
  "Racing",
  "Rafting",
  "Rapping",
  "Reading",
  "Robotics",
  "Rock Climbing",
  "Roller Skating",
  "Rowing",
  "Rugby",
  "Running",
  "Sailing",
  "Scrapbooking",
  "Scuba Diving",
  "Sculpting",
  "Sewing",
  "Shopping",
  "Singing",
  "Skateboarding",
  "Sketching",
  "Skiing",
  "Skydiving",
  "Snorkeling",
  "Snowboarding",
  "Soap Making",
  "Soccer",
  "Socializing",
  "Songwriting",
  "Stamp Collecting",
  "Stand-up Comedy",
  "Stargazing",
  "Streaming",
  "Surfing",
  "Sushi Making",
  "Swimming",
  "Table Tennis",
  "Tattoo Art",
  "Tea Tasting",
  "Tennis",
  "Theater",
  "Thrifting",
  "Traveling",
  "Trekking",
  "Trivia",
  "Ukulele",
  "Urban Exploration",
  "UX Design",
  "Video Editing",
  "Video Games",
  "Vinyl Records",
  "Violin",
  "Vlogging",
  "Volleyball",
  "Volunteering",
  "Watercolor Painting",
  "Weightlifting",
  "Whittling",
  "Wildlife Photography",
  "Windsurfing",
  "Wine Tasting",
  "Woodworking",
  "Writing",
  "Yoga",
  "Yo-yoing",
  "Zumba",
];

export const interestOptions = interests.map((interest) => ({
  label: interest,
  value: interest,
}));
